pets: dog.o pet.o petStore.o
	c++ dog.o pet.o petStore.o  -o pets

dog.o: dog.cpp dog.h
	c++ -c dog.cpp

pet.o: pet.cpp pet.h
	c++ -c pet.cpp

petStore.o: petStore.cpp
	c++ -c petStore.cpp


